stages:
  - docker      # Docker images necessary for the next stages
  - build       # Binary generation
  - docker-bin  # Docker images that contain binaries
  - test        # Tests, documentation
  - deploy      # Final container generation

variables:
  JDK_IMAGE: "openjdk:11"
  JS_CHROME_IMAGE: "$CI_REGISTRY_IMAGE/js-chrome:$CI_PIPELINE_IID"
  JS_CHROME_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/js-chrome:latest"
  SERVER_BIN_IMAGE: "$CI_REGISTRY_IMAGE/server:$CI_PIPELINE_IID"
  SERVER_BIN_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/server:latest"

# *** Phantom Jobs *** #

.gradle:
  before_script: &prepare_gradle
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

.docker-build:
  image: docker:19.03
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  tags:
    - docker

.docker-latest:
  extends: .docker-build
  variables:
    GIT_STRATEGY: none
  stage: deploy

.with-database:
  services:
    - mongo:latest
  variables:
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "development-password"
    formulaide_host: "mongo"
    formulaide_port: 27017
    formulaide_database: "formulaide"
    formulaide_username: "root"
    formulaide_password: "development-password"

# *** Docker *** #

docker-js-chrome:
  extends: .docker-build
  stage: docker
  script:
    - docker pull $JS_CHROME_IMAGE_LATEST || true
    - >
      docker build
      --pull
      --cache-from $JS_CHROME_IMAGE_LATEST
      --tag $JS_CHROME_IMAGE
      -f $CI_PROJECT_DIR/client/build.dockerfile
      .
    - docker push $JS_CHROME_IMAGE

# *** Build *** #

dokka:
  image: $JDK_IMAGE
  stage: build
  extends: [ .gradle ]
  needs: []
  before_script:
    - *prepare_gradle
  script:
    # ui:assemble is needed because of https://github.com/Kotlin/dokka/issues/1455
    - "./gradlew ui:assemble dokkaHtmlMultiModule"
  artifacts:
    paths:
      - build/dokka/htmlMultiModule/

server-bin:
  image: $JDK_IMAGE
  extends: [ .gradle ]
  stage: build
  needs: []
  before_script:
    - *prepare_gradle
  script:
    - "./gradlew server:assembleDist"
  artifacts:
    paths:
      - server/build/distributions

# *** Docker Binaries *** #

server-bin-docker:
  extends: [ .docker-build ]
  stage: docker-bin
  dependencies: [ server-bin ]
  needs: [ server-bin ]
  script:
    - docker pull $SERVER_BIN_IMAGE_LATEST || true
    - cd server
    - >
      docker build
      --pull
      --cache-from $SERVER_BIN_IMAGE_LATEST
      --tag $SERVER_BIN_IMAGE
      -f $CI_PROJECT_DIR/server/Dockerfile
      .
    - docker push $SERVER_BIN_IMAGE

# *** Test *** #

client-js-test:
  image: $JS_CHROME_IMAGE
  stage: test
  extends: [ .gradle, .with-database ]
  needs: [ docker-js-chrome, server-bin ]
  dependencies: [ server-bin ]
  before_script:
    - *prepare_gradle
    - mv server/build/distributions/server*.tar server.tar
    - tar -xf server.tar
  script:
    - "formulaide_allow_init=true ./server-*/bin/server --init &"
    - sleep 5
    - "./gradlew :client:jsBrowserTest"
  artifacts:
    reports:
      junit: client/build/test-results/jsBrowserTest/**/TEST-*.xml
  retry: 2

ui-test:
  image: $JS_CHROME_IMAGE
  stage: test
  extends: [ .gradle ]
  needs: [ docker-js-chrome ]
  before_script:
    - *prepare_gradle
  script:
    - "./gradlew :ui:browserTest"
  artifacts:
    reports:
      junit: ui/build/test-results/browserTest/**/TEST-*.xml

database-test:
  image: $JDK_IMAGE
  stage: test
  extends: [ .gradle, .with-database ]
  needs: []
  before_script:
    - *prepare_gradle
  script:
    - "./gradlew :database:test :database:printCoverage"
  artifacts:
    reports:
      junit: database/build/test-results/test/**/TEST-*.xml
  coverage: '/^Coverage:\s(\d+\.\d+%)/'

server-test:
  image: $JDK_IMAGE
  stage: test
  extends: [ .gradle, .with-database ]
  needs: []
  before_script:
    - *prepare_gradle
  script:
    - "./gradlew :server:test :server:printCoverage"
  artifacts:
    reports:
      junit: server/build/test-results/test/**/TEST-*.xml
  coverage: '/^Coverage:\s(\d+\.\d+%)/'

# *** Deploy *** #

docker-js-chrome-latest:
  extends: .docker-latest
  script:
    - docker pull $JS_CHROME_IMAGE
    - docker tag $JS_CHROME_IMAGE $JS_CHROME_IMAGE_LATEST
    - docker push $JS_CHROME_IMAGE_LATEST
  only:
    - main

server-bin-docker-latest:
  extends: .docker-latest
  script:
    - docker pull $SERVER_BIN_IMAGE
    - docker tag $SERVER_BIN_IMAGE $SERVER_BIN_IMAGE_LATEST
    - docker push $SERVER_BIN_IMAGE_LATEST
  only:
    - main

pages:
  image: alpine:latest
  stage: deploy
  dependencies: [ dokka, server-bin ]
  needs: [ dokka, server-bin ]
  script:
    - mkdir -p public/documentation public/bin
    - mv build/dokka/htmlMultiModule/* public/documentation/
    - mv server/build/distributions/server*.tar public/bin/server.tar
    - mv server/build/distributions/server*.zip public/bin/server.zip
  artifacts:
    paths:
      - public
  only:
    - main
