version: "3.6"

services:
  mongo:
    image: "mongo"
    volumes:
      - data:/data/db
    networks: [ database ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  server:
    image: "registry.gitlab.com/arcachon-ville/formulaide/server:latest"
    ports:
      - target: 8000
        published: 8002
        protocol: tcp
    depends_on: [ mongo ]
    networks: [ database ]
    environment:
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"
      formulaide_jwt_secret: "some basic secret"

volumes:
  data:
    name: data

networks:
  database:
