version: "3.6"

services:
  mongo:
    image: "mongo"
    restart: unless-stopped
    volumes:
      - data:/data/db
    networks: [ database ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  mongo-express:
    image: "mongo-express"
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on: [ mongo ]
    networks: [ database ]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "development-password"

  server:
    image: "registry.gitlab.com/arcachon-ville/formulaide/server:latest"
    restart: unless-stopped
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
    depends_on: [ mongo ]
    networks: [ database ]
    environment:
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"

volumes:
  data:
    name: data

networks:
  database:
