version: "3.6"

services:
  mongo:
    deploy:
      replicas: 1
      update_config:
        delay: 10s

  server:
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
    deploy:
      replicas: 2
      update_config:
        delay: 10s
