version: "3.6"

# Docker Compose configuration for Formulaide

# Development environment:
#
# Start locally:
#   docker-compose up -d

# Production environment:
#
# Start locally:
#   docker-compose up -f docker-compose.yml -f docker-compose.yml up -d
# Deploy to a Docker Swarm:
#   docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml formulaide
#
# To create/administrate a Docker Swarm, see: https://docs.docker.com/engine/swarm/

services:
  mongo:
    image: "mongo"
    volumes:
      - data:/data/db
    networks: [ database ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  server:
    image: "registry.gitlab.com/arcachon-ville/formulaide/server:latest"
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
    depends_on: [ mongo ]
    networks: [ database ]
    environment:
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"

volumes:
  data:
    name: data

networks:
  database:
