version: "3.8"

services:
  mongo:
    image: "mongo"
    restart: unless-stopped
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks: [ mongodb_network ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  mongo-express:
    image: "mongo-express"
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on: [ mongo ]
    networks: [ mongodb_network ]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "development-password"

volumes:
  data:
    name: data

networks:
  mongodb_network:
    name: mongodb_network
