apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-formulaide-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{ .Values.config.host }}
      secretName: tls-formulaide-secret
  ingressClassName: nginx
  rules:
    - host: {{ .Values.config.host }}
      http:
        paths:
          - path: /?(.*)
            backend:
              service:
                name: {{ .Release.Name }}-formulaide-service
                port:
                  name: formulaide-http
            pathType: Prefix
