apiVersion: v1
kind: Secret
stringData:
  host: "{{ .Release.Name }}-formulaide-database"
  port: "{{ .Values.mongodb.service.ports.mongodb }}"
  database: "{{ .Values.database }}"
  username: "{{ .Values.mongodb.auth.rootUser }}"
  password: "{{ .Values.mongodb.auth.rootPassword }}"
  report_email: "{{ .Values.config.report_email }}"
  help_url: "{{ .Values.config.help_page }}"
  pdf_left: "{{ .Values.config.pdf_first_image }}"
  pdf_right: "{{ .Values.config.pdf_second_image }}"
  jwt_secret: "{{ .Values.security.jwt_secret }}"
type: Opaque
metadata:
  name: {{ .Release.Name }}-formulaide-secret
