apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-formulaide-service
spec:
  ports:
    - port: 8000
      name: formulaide-http
      targetPort: 9000
  selector:
    app: {{ .Release.Name }}-ktor
