version: "3.6"

services:
  mongo:
    image: "mongo:6.0.3"
    volumes:
      - data2:/data/db
    networks: [ database ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  server:
    # Replace by a specific version. Do not use 'latest' in production!
    # https://gitlab.com/opensavvy/formulaide/-/releases
    image: "registry.gitlab.com/opensavvy/formulaide/server:latest"
    depends_on: [ mongo ]
    networks: [ database, internal-proxy ]
    environment:
      # Coordonnées de la base de données
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"
      formulaide_report_email: "formulaide@opensavvy.dev"

  proxy:
    image: "caddy:2.6.2-alpine"
    depends_on: [ server ]
    networks: [ internal-proxy ]
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  data2:
    name: data2
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  database:
  internal-proxy:
