version: "3.6"

services:
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - ./database:/root/dump

  server:
    ports:
      - target: 8000
        published: 8002
        protocol: tcp

  mongo-express:
    image: "mongo-express:0.32.0"
    ports:
      - "8081:8081"
    depends_on: [ mongo ]
    networks: [ database ]
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "development-password"

networks:
  database:
    name: database_dev
  internal-proxy:
    name: internal_proxy_dev
