version: "3.6"

services:
  mongo:
    deploy:
      replicas: 1
      update_config:
        delay: 30s

  server:
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
    deploy:
      replicas: 1
      update_config:
        delay: 30s

  proxy:
    image: "caddy:2.4.3-alpine"
    command: "caddy reverse-proxy --from localhost --to server:8000"
    depends_on: [ server ]
    networks: [ internal-proxy ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      replicas: 1
      update_config:
        delay: 60s
