version: "3.6"

services:
  mongo:
    deploy:
      replicas: 1
      update_config:
        delay: 30s

  server:
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
    deploy:
      replicas: 1
      update_config:
        delay: 30s

  proxy:
    command: "caddy reverse-proxy --from localhost --to server:8000"
    ports:
      - "80:80"
      - "443:443"
