version: "3.6"

services:
  mongo:
    image: "mongo:4.4.10"
    volumes:
      - data:/data/db
    networks: [ database ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  server:
    image: "registry.gitlab.com/opensavvy/formulaide/server:latest"  # Replace by a specific version. Do not use 'latest' in production!
    depends_on: [ mongo ]
    networks: [ database, internal-proxy ]
    environment:
      # Coordonnées de la base de données
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"
      formulaide_report_email: "formulaide@opensavvy.dev"
      # Images affichées dans les récépissés en PDF
      formulaide_pdf_image_left_url: ""
      formulaide_pdf_image_right_url: ""

  proxy:
    image: "caddy:2.6.2-alpine"
    depends_on: [ server ]
    networks: [ internal-proxy ]
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  data:
    name: data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  database:
  internal-proxy:
