version: "3.6"

services:
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - ./database:/root/dump

  server:
    pull_policy: always
    ports:
      - target: 9000
        published: 9002
        protocol: tcp

  proxy:
    command: "caddy reverse-proxy --from api.localhost --to 172.17.0.1:8000"
    ports:
      - "8443:443"

networks:
  internal-proxy:
    name: internal_proxy_dev
