version: "3.6"

services:
  mongo:
    image: "mongo:4.4.8"
    volumes:
      - data:/data/db
    networks: [ database ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "development-password"

  server:
    image: "registry.gitlab.com/arcachon-ville/formulaide/server:0.15"
    depends_on: [ mongo ]
    networks: [ database, internal-proxy ]
    environment:
      formulaide_host: "mongo"
      formulaide_port: 27017
      formulaide_database: "formulaide"
      formulaide_username: "root"
      formulaide_password: "development-password"
      formulaide_jwt_secret: "some basic secret"

volumes:
  data:
    name: data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

networks:
  database:
  internal-proxy:
