variables:
  helm_image_name: "$CI_REGISTRY_IMAGE/helm"
  helm_image: "$helm_image_name:$build_version"

.helm:image:
  variables:
    image: "$CI_REGISTRY_IMAGE/helm"
    docker_context: .gitlab
    dockerfile: .gitlab/helm.dockerfile

helm:docker-build:
  extends: [ .docker-build, .helm:image ]
  stage: docker

helm:docker-push:
  extends: [ .docker-rename-latest, .helm:image ]
  stage: deploy

helm:package:
  image: $helm_image
  stage: build
  needs: [ environment, helm:docker-build ]
  script:
    - cd helm
    - helm dependency update
    - helm lint
    - helm package --version $CURRENT_VERSION --app-version $CURRENT_VERSION .
  artifacts:
    when: always
    paths:
      - helm/formulaide-*.tgz
  only:
    - merge_requests
    - main
    - tags

helm:review:
  image: $helm_image
  stage: deploy
  needs: [ environment, helm:package ]
  dependencies: [ helm:package ]
  script:
    - helm upgrade --install formulaide-dev helm/formulaide-*.tgz
  only:
    - merge_requests
