# Formulaide Helm configuration
# This file contains the default values for Formulaide development
# Unless explicitly mentioned, you can keep the default values

# General Formulaide configuration
config:
  # When a user uses the 'report a problem' button, Formulaide generates an email in the user's client, that is pre-filled
  # to be sent at this address:
  report_email: "formulaide@opensavvy.dev"  # this is the OpenSavvy Formulaide Service Desk on GitLab

  # The domain name on which you will deploy Formulaide.
  host: "formulaide.opensavvy.dev"

  # Formulaide image
  image: "registry.gitlab.com/opensavvy/formulaide/server"
  version: "latest"
  # Do not use 'latest' in production!
  # https://gitlab.com/opensavvy/formulaide/-/releases

  # Number of replicas of the Formulaide backend.
  replicas: 2

mongodb:
  architecture: "standalone"

  auth:
    # The credentials of the database user
    # The Formulaide backend uses this account to communicate with the database
    # If you want to change this, you need to either recreate the database, or manually switch the existing account's
    # password directly through the MongoDB API.
    # DO NOT USE THE DEFAULT PASSWORD IN PRODUCTION.
    rootUser: "root"
    rootPassword: "development-password"

  # The DNS name of the database.
  nameOverride: "formulaide-database"

  nodeSelector:
    # The database will only run on nodes that have the label 'database'
    database: "true"

  persistence:
    size: 1Gi

# The name of the database to create in the MongoDB instance.
database: "formulaide"
